version: '3'
services:
  db:
    container_name: products-mysql
    platform: linux/x86_64
    image: mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: nodejs_products
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
